import os

Asset_Path = (
    "/home/Prateek/Documents/Shi_I_Make/Projects/college_Project/Assets/Sprites/Cards/"
)

Card_Files = [
    "/Assets/Sprites/Cards/card-clubs-1.png",
    "/Assets/Sprites/Cards/card-clubs-2.png",
    "/Assets/Sprites/Cards/card-clubs-3.png",
    "/Assets/Sprites/Cards/card-clubs-4.png",
    "/Assets/Sprites/Cards/card-clubs-5.png",
    "/Assets/Sprites/Cards/card-clubs-6.png",
    "/Assets/Sprites/Cards/card-clubs-7.png",
    "/Assets/Sprites/Cards/card-clubs-8.png",
    "/Assets/Sprites/Cards/card-clubs-9.png",
    "/Assets/Sprites/Cards/card-clubs-10.png",
    "/Assets/Sprites/Cards/card-clubs-11.png",
    "/Assets/Sprites/Cards/card-clubs-12.png",
    "/Assets/Sprites/Cards/card-clubs-13.png",
    "/Assets/Sprites/Cards/card-diamonds-1.png",
    "/Assets/Sprites/Cards/card-diamonds-2.png",
    "/Assets/Sprites/Cards/card-diamonds-3.png",
    "/Assets/Sprites/Cards/card-diamonds-4.png",
    "/Assets/Sprites/Cards/card-diamonds-5.png",
    "/Assets/Sprites/Cards/card-diamonds-6.png",
    "/Assets/Sprites/Cards/card-diamonds-7.png",
    "/Assets/Sprites/Cards/card-diamonds-8.png",
    "/Assets/Sprites/Cards/card-diamonds-9.png",
    "/Assets/Sprites/Cards/card-diamonds-10.png",
    "/Assets/Sprites/Cards/card-diamonds-11.png",
    "/Assets/Sprites/Cards/card-diamonds-12.png",
    "/Assets/Sprites/Cards/card-diamonds-13.png",
    "/Assets/Sprites/Cards/card-hearts-1.png",
    "/Assets/Sprites/Cards/card-hearts-2.png",
    "/Assets/Sprites/Cards/card-hearts-3.png",
    "/Assets/Sprites/Cards/card-hearts-4.png",
    "/Assets/Sprites/Cards/card-hearts-5.png",
    "/Assets/Sprites/Cards/card-hearts-6.png",
    "/Assets/Sprites/Cards/card-hearts-7.png",
    "/Assets/Sprites/Cards/card-hearts-8.png",
    "/Assets/Sprites/Cards/card-hearts-9.png",
    "/Assets/Sprites/Cards/card-hearts-10.png",
    "/Assets/Sprites/Cards/card-hearts-11.png",
    "/Assets/Sprites/Cards/card-hearts-12.png",
    "/Assets/Sprites/Cards/card-hearts-13.png",
    "/Assets/Sprites/Cards/card-spades-1.png",
    "/Assets/Sprites/Cards/card-spades-2.png",
    "/Assets/Sprites/Cards/card-spades-3.png",
    "/Assets/Sprites/Cards/card-spades-4.png",
    "/Assets/Sprites/Cards/card-spades-5.png",
    "/Assets/Sprites/Cards/card-spades-6.png",
    "/Assets/Sprites/Cards/card-spades-7.png",
    "/Assets/Sprites/Cards/card-spades-8.png",
    "/Assets/Sprites/Cards/card-spades-9.png",
    "/Assets/Sprites/Cards/card-spades-10.png",
    "/Assets/Sprites/Cards/card-spades-11.png",
    "/Assets/Sprites/Cards/card-spades-12.png",
    "/Assets/Sprites/Cards/card-spades-13.png",
]

CARD_PATHS = [os.path.join(Asset_Path, filename) for filename in Card_Files]
